services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      FAST_LLM: google_vertexai:gemini-2.5-flash-preview-05-20
      SMART_LLM: google_vertexai:gemini-2.5-pro-preview-05-06
      STRATEGIC_LLM: google_vertexai:gemini-2.5-pro-preview-05-06
      EMBEDDING: google_vertexai:text-embedding-004
      GOOGLE_APPLICATION_CREDENTIALS: /app/application_default_credentials.json
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code
    working_dir: /code/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - verifix-devnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      VITE_BACKEND_URL: http://backend:8000
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    networks:
      - verifix-devnet

networks:
  verifix-devnet:
    driver: bridge
